In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [1]:
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_17adace0eaa748b4bc4c5cfb205b3d29 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='G3DrOl9kA5jiYcM5Gh_C6ZU7TtPILiC-Oqi5Q8bZqK4e',
    ibm_auth_endpoint="https://iam.eu-gb.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_17adace0eaa748b4bc4c5cfb205b3d29.get_object(Bucket='mindbenders-donotdelete-pr-tco3biolcmggvm',Key='Smart Investment Prediction.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()

Grade of the company  No. of offline projects  No. of Client projects  \
0                     1                      256                      85   
1                     1                      256                      85   
2                     1                      256                      85   
3                     1                      256                      85   
4                     2                      261                      92   

   Net_turnover  share_price  Prediction  
0       1265242       250.16           0  
1       1265243       250.15           0  
2       1265244       250.14           0  
3       1265245       250.13           1  
4       1625345       425.30           0

In [2]:
dataset

Grade of the company  No. of offline projects  No. of Client projects  \
0                      1                      256                      85   
1                      1                      256                      85   
2                      1                      256                      85   
3                      1                      256                      85   
4                      2                      261                      92   
5                      5                      355                     125   
6                      4                      304                     112   
7                      5                      355                     125   
8                      3                      282                     106   
9                      4                      304                     112   
10                     2                      261                      92   
11                     5                      355                     125   
12                     5                      355                     125   
13                     4                      304                     112   
14                     1                      256                      85   
15                     2                      261                      92   
16                     3                      282                     106   
17                     1                      256                      85   
18                     5                      355                     125   
19                     5                      355                     125   
20                     4                      304                     112   
21                     4                      304                     112   
22                     2                      261                      92   
23                     2                      261                      92   
24                     3                      282                     106   
25                     3                      282                     106   
26                     1                      256                      85   
27                     1                      256                      85   
28                     4                      304                     112   
29                     4                      304                     112   
..                   ...                      ...                     ...   
69                     3                      282                     106   
70                     1                      255                      85   
71                     5                      355                     125   
72                     4                      304                     112   
73                     1                      255                      85   
74                     5                      355                     125   
75                     2                      261                      92   
76                     4                      304                     112   
77                     5                      355                     125   
78                     3                      282                     106   
79                     2                      261                      92   
80                     1                      255                      85   
81                     4                      304                     112   
82                     5                      355                     125   
83                     2                      261                      92   
84                     4                      304                     112   
85                     5                      355                     125   
86                     1                      255                      85   
87                     2                      261                      92   
88                     3                      282                     106   


In [3]:
x= dataset.iloc[:,0:5]

In [4]:
x

Grade of the company  No. of offline projects  No. of Client projects  \
0                      1                      256                      85   
1                      1                      256                      85   
2                      1                      256                      85   
3                      1                      256                      85   
4                      2                      261                      92   
5                      5                      355                     125   
6                      4                      304                     112   
7                      5                      355                     125   
8                      3                      282                     106   
9                      4                      304                     112   
10                     2                      261                      92   
11                     5                      355                     125   
12                     5                      355                     125   
13                     4                      304                     112   
14                     1                      256                      85   
15                     2                      261                      92   
16                     3                      282                     106   
17                     1                      256                      85   
18                     5                      355                     125   
19                     5                      355                     125   
20                     4                      304                     112   
21                     4                      304                     112   
22                     2                      261                      92   
23                     2                      261                      92   
24                     3                      282                     106   
25                     3                      282                     106   
26                     1                      256                      85   
27                     1                      256                      85   
28                     4                      304                     112   
29                     4                      304                     112   
..                   ...                      ...                     ...   
69                     3                      282                     106   
70                     1                      255                      85   
71                     5                      355                     125   
72                     4                      304                     112   
73                     1                      255                      85   
74                     5                      355                     125   
75                     2                      261                      92   
76                     4                      304                     112   
77                     5                      355                     125   
78                     3                      282                     106   
79                     2                      261                      92   
80                     1                      255                      85   
81                     4                      304                     112   
82                     5                      355                     125   
83                     2                      261                      92   
84                     4                      304                     112   
85                     5                      355                     125   
86                     1                      255                      85   
87                     2                      261                      92   
88                     3                      282                     106   


In [5]:
x= dataset.iloc[:,0:5].values

In [6]:
x

array([[  1.00000000e+00,   2.56000000e+02,   8.50000000e+01,
          1.26524200e+06,   2.50160000e+02],
       [  1.00000000e+00,   2.56000000e+02,   8.50000000e+01,
          1.26524300e+06,   2.50150000e+02],
       [  1.00000000e+00,   2.56000000e+02,   8.50000000e+01,
          1.26524400e+06,   2.50140000e+02],
       [  1.00000000e+00,   2.56000000e+02,   8.50000000e+01,
          1.26524500e+06,   2.50130000e+02],
       [  2.00000000e+00,   2.61000000e+02,   9.20000000e+01,
          1.62534500e+06,   4.25300000e+02],
       [  5.00000000e+00,   3.55000000e+02,   1.25000000e+02,
          4.52451250e+07,   1.24523000e+03],
       [  4.00000000e+00,   3.04000000e+02,   1.12000000e+02,
          1.21365270e+07,   7.30580000e+02],
       [  5.00000000e+00,   3.55000000e+02,   1.25000000e+02,
          4.52445250e+07,   1.24523000e+03],
       [  3.00000000e+00,   2.82000000e+02,   1.06000000e+02,
          3.02825300e+06,   6.14200000e+02],
       [  4.00000000e+00,   3.0400000

In [7]:
type(x)

numpy.ndarray

In [8]:
y= dataset.iloc[:,-1].values

In [9]:
y

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0])

In [10]:
y= dataset.iloc[:,-1]

In [11]:
y

0     0
1     0
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    1
13    1
14    0
15    1
16    0
17    0
18    1
19    1
20    1
21    1
22    0
23    0
24    1
25    0
26    0
27    0
28    1
29    1
     ..
69    1
70    0
71    1
72    1
73    0
74    0
75    1
76    0
77    1
78    0
79    0
80    1
81    0
82    0
83    1
84    0
85    1
86    1
87    0
88    0
89    1
90    0
91    1
92    1
93    1
94    0
95    0
96    1
97    1
98    0
Name: Prediction, Length: 99, dtype: int64

In [12]:
type(y)

pandas.core.series.Series

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
x_train

array([[  4.00000000e+00,   3.04000000e+02,   1.12000000e+02,
          1.21875230e+07,   7.30800000e+02],
       [  3.00000000e+00,   2.82000000e+02,   1.06000000e+02,
          3.02725300e+06,   6.14280000e+02],
       [  1.00000000e+00,   2.56000000e+02,   8.50000000e+01,
          1.26524500e+06,   2.50130000e+02],
       [  5.00000000e+00,   3.55000000e+02,   1.25000000e+02,
          4.52458250e+07,   1.24571000e+03],
       [  5.00000000e+00,   3.55000000e+02,   1.25000000e+02,
          4.52458950e+07,   1.24523000e+03],
       [  2.00000000e+00,   2.61000000e+02,   9.20000000e+01,
          1.67834600e+06,   4.25130000e+02],
       [  4.00000000e+00,   3.04000000e+02,   1.12000000e+02,
          1.21365270e+07,   7.30580000e+02],
       [  3.00000000e+00,   2.82000000e+02,   1.06000000e+02,
          3.02515300e+06,   6.14360000e+02],
       [  5.00000000e+00,   3.55000000e+02,   1.25000000e+02,
          4.52455250e+07,   1.24586000e+03],
       [  4.00000000e+00,   3.0400000

In [15]:
from sklearn.tree import DecisionTreeRegressor
regressor= DecisionTreeRegressor(random_state=0)
regressor.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [16]:
y_predict=regressor.predict(x_test)


In [17]:
y_predict

array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  0.,  0.])

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)

In [19]:
cm

array([[7, 3],
       [5, 5]])

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

0.59999999999999998

In [21]:
regressor.predict([[4,304,112,12136823,730.88]])

array([ 0.])

In [22]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
2019-07-15 09:51:37,826 - watson_machine_learning_client.metanames - WARNING - 'AUTHOR_EMAIL' meta prop is deprecated. It will be ignored.
2019-07-15 09:52:06,424 - watson_machine_learning_client.wml_client_error - WARNING - Deployment creation failed. Error: 402. {"trace":"7a4b8bf86cfe68d80d8d8c7055ba7fe6","errors":[{"code":"deployments_plan_limit_reached","message":"Current plan 'lite' only allows 5 deployments"}]}


In [31]:
wml_credentials={
    "url":"https://eu-gb.ml.cloud.ibm.com",
    "acess_key":"GtUTj5RuSeC58PzBJ2c2sZYqAo9GZcLD75GGsxpMG3da" ,
    "username": "2d90fdc0-1fc8-4780-b16c-ee62cfea4a50",
    "password": "78c3fe9d-ed9f-4985-92c6-363fb7847690",
    "instance_id":  "8313129f-ebbb-4ccd-b96d-1ce3f239f9a3"
}

In [32]:
client=WatsonMachineLearningAPIClient(wml_credentials)

In [33]:
model_props={client.repository.ModelMetaNames.AUTHOR_NAME:"IBM",
             client.repository.ModelMetaNames.AUTHOR_EMAIL:"ibm@ibm.com",
             client.repository.ModelMetaNames.NAME:"DecisionTreeRegressor"}

In [34]:
model_artifact=client.repository.store_model(regressor,meta_props=model_props)

In [35]:
published_model_uid=client.repository.get_model_uid(model_artifact)

In [36]:
created_deployment=client.deployments.create(published_model_uid,name="DecisionTreeRegressor")



#######################################################################################

Synchronous deployment creation for uid: 'c67aefd3-d934-43ae-a6dd-009fbbcaf6de' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='d33ce955-1905-4085-9de4-63e4e3ef14df'
------------------------------------------------------------------------------------------------




In [38]:
scoring_endpoint=client.deployments.get_scoring_url(created_deployment)

In [39]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/8313129f-ebbb-4ccd-b96d-1ce3f239f9a3/deployments/d33ce955-1905-4085-9de4-63e4e3ef14df/online'