In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('bike2.csv')

In [3]:
dataset

Gender  YearlyIncome  NumberCarsOwned  Age  BikeBuyer
0         0         90000                0   50          1
1         0         60000                1   51          1
2         0         60000                1   51          1
3         1         70000                1   49          1
4         1         80000                4   48          1
5         0         70000                1   51          1
6         1         70000                1   51          1
7         0         60000                2   52          1
8         1         60000                3   52          1
9         0         70000                1   52          1
10        1         70000                1   53          1
11        0         60000                4   53          1
12        1        100000                2   49          0
13        0        100000                3   48          0
14        1        100000                3   48          0
15        1         30000                1   38          1
16        0         30000                1   37          1
17        1         20000                2   72          1
18        0         30000                2   72          1
19        0         40000                2   39          0
20        0         40000                2   38          1
21        1         40000                1   38          1
22        0         40000                1   38          1
23        0         40000                1   38          0
24        0         60000                2   38          0
25        0         10000                2   71          1
26        0         30000                2   70          1
27        0         30000                2   70          1
28        1         30000                2   70          1
29        0         30000                2   70          1
..      ...           ...              ...  ...        ...
516       1         30000                1   62          1
517       1         40000                1   62          0
518       0         40000                1   61          0
519       0         40000                1   61          0
520       1         40000                1   61          0
521       1         40000                1   61          0
522       0         80000                0   61          1
523       0         40000                1   60          1
524       1         40000                1   61          0
525       1         40000                1   61          1
526       1         40000                1   60          1
527       1         40000                1   60          0
528       1         40000                1   59          1
529       0         40000                1   59          1
530       0         40000                1   59          0
531       1         40000                1   60          1
532       1         40000                1   60          0
533       1         40000                1   59          0
534       0         60000                0   58          1
535       0         60000                0   58          1
536       0         60000                0   58          1
537       0         60000                0   58          1
538       1         60000                0   57          1
539       0         60000                0   57          1
540       0         60000                0   58          1
541       0         60000                0   57          1
542       0         20000                0   48          0
543       1         20000                1   49          0
544       0         30000                0   48          0
545       0         30000                0   48          0

[546 rows x 5 columns]

In [4]:
x=dataset.iloc[:,[1,3]].values

In [5]:
y=dataset.iloc[:,4:].values

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
x_train

array([[-0.05087626,  1.1511979 ],
       [-0.05087626, -0.40380973],
       [-0.05087626, -0.56749474],
       [-0.61326514, -1.2222348 ],
       [-0.61326514, -0.89486477],
       [-0.61326514,  0.16908782],
       [-0.89445959, -1.14039229],
       [ 0.23031819, -0.48565224],
       [-0.05087626, -0.15828221],
       [-1.17565403,  0.16908782],
       [-0.61326514,  0.66014286],
       [-1.45684847,  1.0693554 ],
       [-1.45684847, -1.63144733],
       [-0.61326514, -1.71328984],
       [-0.05087626, -0.0764397 ],
       [ 1.6362904 ,  0.49645785],
       [-1.45684847, -1.46776232],
       [ 0.23031819,  1.80593796],
       [-0.89445959, -0.81302226],
       [-0.61326514,  0.49645785],
       [-0.61326514, -1.63144733],
       [ 0.51151263,  0.41461534],
       [ 0.23031819, -0.48565224],
       [-0.05087626, -0.40380973],
       [-1.17565403,  1.47856793],
       [-1.17565403, -0.24012471],
       [-0.89445959, -0.0764397 ],
       [ 1.35509596, -0.97670728],
       [-0.05087626,

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [13]:
y_pred=classifier.predict(x_test)
y_pred


array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0], dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[49, 21],
       [21, 46]], dtype=int64)

In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


0.6934306569343066