In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_e75c441252fc48c9891339a360d9277d = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='TXfdTI_4BnLjlZO9KWvV6NvNLhp-NHwfwT0t6OdApn2N',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_e75c441252fc48c9891339a360d9277d.get_object(Bucket='universityadmissionprediction-donotdelete-pr-omi5zgdl4prmhk',Key='Admission_Predict_Ver1.1.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()



Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              1.00  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [7]:
dataset

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
5             6        330          115                  5  4.5   3.0  9.34   
6             7        321          109                  3  3.0   4.0  8.20   
7             8        308          101                  2  3.0   4.0  7.90   
8             9        302          102                  1  2.0   1.5  8.00   
9            10        323          108                  3  3.5   3.0  8.60   
10           11        325          106                  3  3.5   4.0  8.40   
11           12        327          111                  4  4.0   4.5  9.00   
12           13        328          112                  4  4.0   4.5  9.10   
13           14        307          109                  3  4.0   3.0  8.00   
14           15        311          104                  3  3.5   2.0  8.20   
15           16        314          105                  3  3.5   2.5  8.30   
16           17        317          107                  3  4.0   3.0  8.70   
17           18        319          106                  3  4.0   3.0  8.00   
18           19        318          110                  3  4.0   3.0  8.80   
19           20        303          102                  3  3.5   3.0  8.50   
20           21        312          107                  3  3.0   2.0  7.90   
21           22        325          114                  4  3.0   2.0  8.40   
22           23        328          116                  5  5.0   5.0  9.50   
23           24        334          119                  5  5.0   4.5  9.70   
24           25        336          119                  5  4.0   3.5  9.80   
25           26        340          120                  5  4.5   4.5  9.60   
26           27        322          109                  5  4.5   3.5  8.80   
27           28        298           98                  2  1.5   2.5  7.50   
28           29        295           93                  1  2.0   2.0  7.20   
29           30        310           99                  2  1.5   2.0  7.30   
..          ...        ...          ...                ...  ...   ...   ...   
470         471        320          110                  5  4.0   4.0  9.27   
471         472        311          103                  3  2.0   4.0  8.09   
472         473        327          116                  4  4.0   4.5  9.48   
473         474        316          102                  2  4.0   3.5  8.15   
474         475        308          105                  4  3.0   2.5  7.95   
475         476        300          101                  3  3.5   2.5  7.88   
476         477        304          104                  3  2.5   2.0  8.12   
477         478        309          105                  4  3.5   2.0  8.18   
478         479        318          103                  3  4.0   4.5  8.49   
479         480        325          110                  4  4.5   4.0  8.96   
480         481        321          102                  3  3.5   4.0  9.01   
481         482        323          107                  4  3.0   2.5  8.48   
482         483        328          113                  4  4.0   2.5  8.77   
483         484        304          103                  5  5.0   3.0  7.92   
484         485        317          106                  3  3.5   3.0  7.89   
485         486        311          101                  2  2.5   3.5  8.34   
486         487        319          102                  3  2.5   2.5  8.37   
487         488        327          115                  4  3.5   4.0  9.14   
488         489        322          112                

In [8]:
X = dataset.iloc[:, 1:8].values
X

array([[ 337.  ,  118.  ,    4.  , ...,    4.5 ,    9.65,    1.  ],
       [ 324.  ,  107.  ,    4.  , ...,    4.5 ,    8.87,    1.  ],
       [ 316.  ,  104.  ,    3.  , ...,    3.5 ,    8.  ,    1.  ],
       ..., 
       [ 330.  ,  120.  ,    5.  , ...,    5.  ,    9.56,    1.  ],
       [ 312.  ,  103.  ,    4.  , ...,    5.  ,    8.43,    0.  ],
       [ 327.  ,  113.  ,    4.  , ...,    4.5 ,    9.04,    0.  ]])

In [9]:
y= dataset.iloc[:, [8]].values

In [10]:
y

array([[ 1.  ],
       [ 0.76],
       [ 0.72],
       [ 0.8 ],
       [ 0.65],
       [ 0.9 ],
       [ 0.75],
       [ 0.68],
       [ 0.5 ],
       [ 0.45],
       [ 0.52],
       [ 0.84],
       [ 0.78],
       [ 0.62],
       [ 0.61],
       [ 0.54],
       [ 0.66],
       [ 0.65],
       [ 0.63],
       [ 0.62],
       [ 0.64],
       [ 0.7 ],
       [ 0.94],
       [ 0.95],
       [ 0.97],
       [ 0.94],
       [ 0.76],
       [ 0.44],
       [ 0.46],
       [ 0.54],
       [ 0.65],
       [ 0.74],
       [ 0.91],
       [ 0.9 ],
       [ 0.94],
       [ 0.88],
       [ 0.64],
       [ 0.58],
       [ 0.52],
       [ 0.48],
       [ 0.46],
       [ 0.49],
       [ 0.53],
       [ 0.87],
       [ 0.91],
       [ 0.88],
       [ 0.86],
       [ 0.89],
       [ 0.82],
       [ 0.78],
       [ 0.76],
       [ 0.56],
       [ 0.78],
       [ 0.72],
       [ 0.7 ],
       [ 0.64],
       [ 0.64],
       [ 0.46],
       [ 0.36],
       [ 0.42],
       [ 0.48],
       [ 0.47],
       [

In [11]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X, y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [12]:
y_pred = regressor.predict([[380,60,2.5,2.5,2.5,5,1]])

In [13]:
y_pred

array([ 0.7])

In [14]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
2019-06-18 16:42:15,542 - watson_machine_learning_client.metanames - WARNING - 'AUTHOR_EMAIL' meta prop is deprecated. It will be ignored.


In [15]:
wml_credentials={
    "access_key":"VPYh8brRRQAPBwoeRPa34MWiG4yyE5okIoHVOYlDDal2",
     "instance_id": "885912a1-52ed-4ad8-97a6-5b6937ff9af0",
     "password": "f77f8220-05c6-471c-aa5b-38ea87215cae",
    "url": "https://eu-gb.ml.cloud.ibm.com",
    "username": "e7d6393f-27f2-4ee8-865c-8ce01184fc49"
}

In [16]:
client=WatsonMachineLearningAPIClient(wml_credentials)

In [17]:
model_props={client.repository.ModelMetaNames.AUTHOR_NAME:"IBM",
             client.repository.ModelMetaNames.AUTHOR_EMAIL:"ibm@ibm.com",
             client.repository.ModelMetaNames.NAME:"Decision Tree regression"}

In [18]:
model_artifact=client.repository.store_model(regressor,meta_props=model_props)

In [19]:
published_model_uid=client.repository.get_model_uid(model_artifact)

In [20]:
created_deployment=client.deployments.create(published_model_uid,name="Decision Tree")



#######################################################################################

Synchronous deployment creation for uid: '2ab109bc-6f1b-491e-81d9-48dd82fa80da' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='f45f265d-22b3-4de9-a3c1-6dd66f1adf0a'
------------------------------------------------------------------------------------------------




In [21]:
scoring_endpoint=client.deployments.get_scoring_url(created_deployment)

In [22]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/885912a1-52ed-4ad8-97a6-5b6937ff9af0/deployments/f45f265d-22b3-4de9-a3c1-6dd66f1adf0a/online'