In [1]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#importing the dataset
dataset=pd.read_csv('dataf.csv')
dataset


Cost of Cultivation (`/Hectare) A2+FL  Cost of Cultivation (`/Hectare) C2  \
0                                 9794.05                            23076.74   
1                                10593.15                            16528.68   
2                                13468.82                            19551.90   
3                                17051.66                            24171.65   
4                                17130.55                            25270.26   
5                                23711.44                            33116.82   
6                                29047.10                            50828.83   
7                                29140.77                            44756.72   
8                                29616.09                            42070.44   
9                                29918.97                            44018.18   
10                                8552.69                            12610.85   
11                                9803.89                            16873.17   
12                               12833.04                            21618.43   
13                               12985.95                            18679.33   
14                               14421.98                            26762.09   
15                               13647.10                            17314.20   
16                               21229.01                            30434.61   
17                               22507.86                            30393.66   
18                               22951.28                            30114.45   

    Cost of Production (`/Quintal) C2  Yield (Quintal/ Hectare)   rainfall  \
0                             1941.55                       9.83        20   
1                             2172.46                       7.47        23   
2                             1898.30                       9.59        86   
3                             3670.54                       6.42        48   
4                             2775.80                       8.72        24   
5                             2539.47                      12.69        68   
6                             2003.76                      24.39        42   
7                             2509.99                      17.83        52   
8                             2179.26                      19.05        58   
9                             2127.35                      19.90        63   
10                            1691.66                       6.83        25   
11                            1551.94                      10.29        87   
12                            1882.68                      10.93        52   
13                            2277.68                       8.05        65   
14                            1559.04                      16.69        75   
15                            3484.01                       4.71        43   
16                            2554.91                      11.97        82   
17                            2358.00                      11.98        62   
18                            1918.92                      13.45        42   

         Crop  
0       ARHAR  
1       ARHAR  
2       ARHAR  
3       ARHAR  
4       ARHAR  
5      COTTON  
6      COTTON  
7      COTTON  
8      COTTON  
9      COTTON  
10       GRAM  
11       GRAM  
12       GRAM  
13       GRAM  
14       GRAM  
15  GROUNDNUT  
16  GROUNDNUT  
17  GROUNDNUT  
18  GROUNDNUT

In [3]:
x=dataset.iloc[:,0:-1].values
x

array([[9.794050e+03, 2.307674e+04, 1.941550e+03, 9.830000e+00,
        2.000000e+01],
       [1.059315e+04, 1.652868e+04, 2.172460e+03, 7.470000e+00,
        2.300000e+01],
       [1.346882e+04, 1.955190e+04, 1.898300e+03, 9.590000e+00,
        8.600000e+01],
       [1.705166e+04, 2.417165e+04, 3.670540e+03, 6.420000e+00,
        4.800000e+01],
       [1.713055e+04, 2.527026e+04, 2.775800e+03, 8.720000e+00,
        2.400000e+01],
       [2.371144e+04, 3.311682e+04, 2.539470e+03, 1.269000e+01,
        6.800000e+01],
       [2.904710e+04, 5.082883e+04, 2.003760e+03, 2.439000e+01,
        4.200000e+01],
       [2.914077e+04, 4.475672e+04, 2.509990e+03, 1.783000e+01,
        5.200000e+01],
       [2.961609e+04, 4.207044e+04, 2.179260e+03, 1.905000e+01,
        5.800000e+01],
       [2.991897e+04, 4.401818e+04, 2.127350e+03, 1.990000e+01,
        6.300000e+01],
       [8.552690e+03, 1.261085e+04, 1.691660e+03, 6.830000e+00,
        2.500000e+01],
       [9.803890e+03, 1.687317e+04, 1.55194

In [4]:
y=dataset.iloc[:,5:].values
y

array([['ARHAR'],
       ['ARHAR'],
       ['ARHAR'],
       ['ARHAR'],
       ['ARHAR'],
       ['COTTON'],
       ['COTTON'],
       ['COTTON'],
       ['COTTON'],
       ['COTTON'],
       ['GRAM'],
       ['GRAM'],
       ['GRAM'],
       ['GRAM'],
       ['GRAM'],
       ['GROUNDNUT'],
       ['GROUNDNUT'],
       ['GROUNDNUT'],
       ['GROUNDNUT']], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
lb1 = LabelEncoder()
y = lb1.fit_transform(y)

C:\anaconda88\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3])

In [7]:
#splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)



In [8]:
x_test

array([[8.552690e+03, 1.261085e+04, 1.691660e+03, 6.830000e+00,
        2.500000e+01],
       [1.059315e+04, 1.652868e+04, 2.172460e+03, 7.470000e+00,
        2.300000e+01],
       [2.961609e+04, 4.207044e+04, 2.179260e+03, 1.905000e+01,
        5.800000e+01],
       [2.295128e+04, 3.011445e+04, 1.918920e+03, 1.345000e+01,
        4.200000e+01]])

In [9]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
x_test

array([[-1.45988731, -1.54500033, -1.09050956, -1.05724537, -1.65594758],
       [-1.15879519, -1.16303035, -0.28470441, -0.93277204, -1.7565112 ],
       [ 1.64824704,  1.32717095, -0.27330783,  1.31941733,  0.00335212],
       [ 0.66478165,  0.16151824, -0.7096292 ,  0.23027567, -0.80115683]])

In [18]:
#fitting knn to the training set
from sklearn.neighbors import KNeighborClassifier
classifier=KNeighborClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

ImportError: cannot import name 'KNeighborClassifier' from 'sklearn.neighbors' (C:\anaconda88\lib\site-packages\sklearn\neighbors\__init__.py)

In [12]:
#predicting the test set resultsy_pred
y_pred=classifier.predict(x_test)
y_pred

array([0, 0, 1, 3])

In [13]:

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1]], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.75

In [15]:
classifier.predict(np.array([[0.66478165,  0.16151824, -0.7096292 ,  0.23027567, -0.80115683]]))

array([3])