In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt

In [84]:
 dataset=pd.read_csv("Book1.csv")

In [85]:
dataset

Sn NO  User ID Product ID Gender    Age  Occupation City-category  \
0        1  1000001  P00069042      F   0-17          10             A   
1        2  1000001  P00248942      F   0-17          10             A   
2        3  1000001  P00087842      F   0-17          10             A   
3        4  1000001  P00085442      F   0-17          10             A   
4        5  1000002  P00285442      M    55+          16             C   
5        6  1000003  P00193542      M  26-35          15             A   
6        7  1000004  P00184942      M  46-50           7             B   
7        8  1000004  P00346142      M  46-50           7             B   
8        9  1000004   P0097242      M  46-50           7             B   
9       10  1000005  P00274942      M  26-35          20             A   
10      11  1000005  P00251242      M  26-35          20             A   
11      12  1000005  P00014542      M  26-35          20             A   
12      13  1000005  P00031342      M  26-35          20             A   
13      14  1000005  P00145042      M  26-35          20             A   
14      15  1000006  P00231342      F  51-55           9             A   
15      16  1000006  P00190242      F  51-55           9             A   
16      17  1000006   P0096642      F  51-55           9             A   
17      18  1000006  P00058442      F  51-55           9             A   
18      19  1000007  P00036842      M  36-45           1             B   
19      20  1000008  P00249542      M  26-35          12             C   
20      21  1000008  P00220442      M  26-35          12             C   
21      22  1000008  P00156442      M  26-35          12             C   
22      23  1000008  P00213742      M  26-35          12             C   
23      24  1000008  P00214442      M  26-35          12             C   
24      25  1000008  P00303442      M  26-35          12             C   
25      26  1000009  P00135742      M  26-35          17             C   
26      27  1000009  P00039942      M  26-35          17             C   
27      28  1000009  P00161442      M  26-35          17             C   
28      29  1000009  P00078742      M  26-35          17             C   
29      30  1000010  P00085942      F  36-45           1             B   
..     ...      ...        ...    ...    ...         ...           ...   
170    171  1000033  P00351842      M  46-50           3             A   
171    172  1000033  P00145442      M  46-50           3             A   
172    173  1000033  P00344242      M  46-50           3             A   
173    174  1000033  P00327242      M  46-50           3             A   
174    175  1000033  P00241142      M  46-50           3             A   
175    176  1000033  P00219242      M  46-50           3             A   
176    177  1000033  P00057342      M  46-50           3             A   
177    178  1000033  P00165742      M  46-50           3             A   
178    179  1000033  P00154642      M  46-50           3             A   
179    180  1000034  P00192942      F  18-25           0             A   
180    181  1000034  P00247042      F  18-25           0             A   
181    182  1000034  P00150542      F  18-25           0             A   
182    183  1000034  P00347142      F  18-25           0             A   
183    184  1000034  P00326742      F  18-25           0             A   
184    185  1000034  P00085942      F  18-25           0             A   
185    186  1000034  P00330442      F  18-25           0             A   
186    187  1000034  P00327842      F  18-25           0             A   
187    188  1000034  P00218342      F  18-25           0             A   
188    189  1000034  P00259042      F  18-25           0             A   
189    190  1000035  P00102542      M  46-50           1             C   
190    191  1000035  P00285442      M  46-50           1             C   
191    192  1000035  P00121142      M  46-50           1             C   
192    19

In [74]:
 dataset.isnull().any()


Sn NO                 False
User ID               False
Product ID            False
Gender                False
Age                   False
Occupation            False
City-category         False
Current_city          False
Martinal status       False
Product_category-1    False
Product_category-2    False
Product_category-3    False
Purchase              False
dtype: bool

In [55]:
    x=dataset.iloc[:,1:-1].values
x


array([[1000001, 'P00069042', 'F', ..., 3, 0, 0],
       [1000001, 'P00248942', 'F', ..., 1, 6, 14],
       [1000001, 'P00087842', 'F', ..., 12, 0, 0],
       ...,
       [1000036, 'P00127442', 'M', ..., 1, 2, 15],
       [1000036, 'P00345642', 'M', ..., 1, 15, 16],
       [1000036, 'P00357842', 'M', ..., 5, 0, 0]], dtype=object)

In [56]:
y=dataset.iloc[:,12:].values
y

array([[ 8370],
       [15200],
       [ 1422],
       [ 1057],
       [ 7969],
       [15227],
       [19215],
       [15854],
       [15686],
       [ 7871],
       [ 5254],
       [ 3957],
       [ 6073],
       [15665],
       [ 5378],
       [ 2079],
       [13055],
       [ 8851],
       [11788],
       [19614],
       [ 8584],
       [ 9872],
       [ 9743],
       [ 5982],
       [11927],
       [16662],
       [ 5887],
       [ 6973],
       [ 5391],
       [16352],
       [ 8886],
       [ 5875],
       [ 8854],
       [10946],
       [ 5152],
       [ 7089],
       [12909],
       [ 8770],
       [15212],
       [15705],
       [ 7947],
       [18963],
       [ 8718],
       [16406],
       [12642],
       [10007],
       [11562],
       [ 6171],
       [19327],
       [ 8027],
       [15246],
       [ 6865],
       [ 5839],
       [15912],
       [12107],
       [ 5848],
       [19653],
       [ 5958],
       [11415],
       [ 5380],
       [ 3594],
       [ 4209],
       [

In [57]:
 from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()


In [58]:
 x[:,1]=lb.fit_transform(x[:,1])
x


array([[1000001, 30, 'F', ..., 3, 0, 0],
       [1000001, 125, 'F', ..., 1, 6, 14],
       [1000001, 38, 'F', ..., 12, 0, 0],
       ...,
       [1000036, 64, 'M', ..., 1, 2, 15],
       [1000036, 174, 'M', ..., 1, 15, 16],
       [1000036, 183, 'M', ..., 5, 0, 0]], dtype=object)

In [59]:
 x[:,2]=lb.fit_transform(x[:,2])
x
 

array([[1000001, 30, 0, ..., 3, 0, 0],
       [1000001, 125, 0, ..., 1, 6, 14],
       [1000001, 38, 0, ..., 12, 0, 0],
       ...,
       [1000036, 64, 1, ..., 1, 2, 15],
       [1000036, 174, 1, ..., 1, 15, 16],
       [1000036, 183, 1, ..., 5, 0, 0]], dtype=object)

In [60]:
 x[:,3]=lb.fit_transform(x[:,3])
x


array([[1000001, 30, 0, ..., 3, 0, 0],
       [1000001, 125, 0, ..., 1, 6, 14],
       [1000001, 38, 0, ..., 12, 0, 0],
       ...,
       [1000036, 64, 1, ..., 1, 2, 15],
       [1000036, 174, 1, ..., 1, 15, 16],
       [1000036, 183, 1, ..., 5, 0, 0]], dtype=object)

In [61]:
 x[:,5]=lb.fit_transform(x[:,5])
x


array([[1000001, 30, 0, ..., 3, 0, 0],
       [1000001, 125, 0, ..., 1, 6, 14],
       [1000001, 38, 0, ..., 12, 0, 0],
       ...,
       [1000036, 64, 1, ..., 1, 2, 15],
       [1000036, 174, 1, ..., 1, 15, 16],
       [1000036, 183, 1, ..., 5, 0, 0]], dtype=object)

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state= 0)


In [63]:
 x_test 

array([[1000007, 16, 1, 3, 1, 1, 1, 1, 1, 14, 16],
       [1000033, 182, 1, 4, 3, 0, 1, 1, 5, 0, 0],
       [1000022, 158, 1, 1, 15, 0, 4, 0, 5, 14, 0],
       [1000022, 181, 1, 1, 15, 0, 4, 0, 1, 8, 17],
       [1000033, 84, 1, 4, 3, 0, 1, 1, 8, 16, 0],
       [1000034, 178, 0, 1, 0, 0, 0, 0, 5, 0, 0],
       [1000003, 98, 1, 2, 15, 0, 3, 0, 1, 2, 0],
       [1000027, 54, 1, 2, 11, 2, 1, 1, 2, 17, 0],
       [1000005, 10, 1, 2, 20, 0, 1, 1, 8, 0, 0],
       [1000029, 119, 1, 3, 7, 2, 1, 0, 1, 15, 0],
       [1000015, 85, 1, 2, 7, 0, 1, 0, 8, 0, 0],
       [1000024, 101, 0, 2, 7, 0, 3, 1, 5, 8, 0],
       [1000034, 123, 0, 1, 0, 0, 0, 0, 5, 14, 0],
       [1000029, 180, 1, 3, 7, 2, 1, 0, 1, 5, 0],
       [1000018, 186, 0, 1, 3, 1, 3, 0, 4, 5, 0],
       [1000004, 176, 1, 4, 7, 1, 2, 1, 1, 15, 0],
       [1000010, 27, 0, 3, 1, 1, 4, 1, 3, 4, 0],
       [1000026, 20, 1, 2, 7, 1, 2, 1, 5, 0, 0],
       [1000010, 91, 0, 3, 1, 1, 4, 1, 5, 12, 0],
       [1000018, 57, 0, 1, 3, 1, 3, 0, 1, 2,

In [64]:
 dataset.corr()


Sn NO   User ID  Occupation  Current_city  \
Sn NO               1.000000  0.994459   -0.344006     -0.220720   
User ID             0.994459  1.000000   -0.345723     -0.220376   
Occupation         -0.344006 -0.345723    1.000000      0.037606   
Current_city       -0.220720 -0.220376    0.037606      1.000000   
Martinal status     0.066698  0.046652   -0.280637      0.185550   
Product_category-1  0.121678  0.110074    0.009467     -0.050096   
Product_category-2  0.012040  0.012760   -0.079200     -0.120206   
Product_category-3 -0.136731 -0.133120   -0.081930      0.097375   
Purchase           -0.194392 -0.184043   -0.076750      0.109402   

                    Martinal status  Product_category-1  Product_category-2  \
Sn NO                      0.066698            0.121678            0.012040   
User ID                    0.046652            0.110074            0.012760   
Occupation                -0.280637            0.009467           -0.079200   
Current_city               0.185550           -0.050096           -0.120206   
Martinal status            1.000000            0.113364            0.007420   
Product_category-1         0.113364            1.000000           -0.061337   
Product_category-2         0.007420           -0.061337            1.000000   
Product_category-3        -0.024553           -0.512621            0.013384   
Purchase                  -0.012390           -0.636834            0.018173   

                    Product_category-3  Purchase  
Sn NO                        -0.136731 -0.194392  
User ID                      -0.133120 -0.184043  
Occupation                   -0.081930 -0.076750  
Current_city                  0.097375  0.109402  
Martinal status              -0.024553 -0.012390  
Product_category-1           -0.512621 -0.636834  
Product_category-2            0.013384  0.018173  
Product_category-3            1.000000  0.420647  
Purchase                      0.420647  1.000000

In [77]:
 from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(x_train,y_train)

F:\New folder\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [78]:
 y_pred=regressor.predict(x_test)


In [79]:
y_pred

array([15665.6,  4925. ,  6499.9, 14562.5,  5781.9,  6689.7, 12879.2,
        8790.9,  4566.6, 12062.1,  6283.4,  6312.3,  8416.5, 14969.5,
        1921.8, 14900.4,  8475. ,  4468.7,  8393.6, 15544. ,  5459.3,
        8449.3,  5805.8,  6707.9,  5732.1, 13313.7,  6987.1,  7693.2,
        4066.5,  8506.1, 16356. , 10135.3,  6949.8, 13754.8,  6489.7,
        9777.8, 13865.6,  5978.7,  6442.6,  5392.7])

In [82]:
y_test

array([[11788],
       [ 5265],
       [ 5168],
       [12099],
       [ 7994],
       [ 5329],
       [15227],
       [15903],
       [ 6073],
       [19068],
       [ 4209],
       [ 6940],
       [ 8593],
       [15511],
       [  697],
       [15854],
       [10946],
       [ 1848],
       [ 8770],
       [19672],
       [ 5942],
       [16500],
       [10007],
       [ 8596],
       [ 3594],
       [ 7601],
       [ 6996],
       [ 7165],
       [  584],
       [12642],
       [13055],
       [ 5848],
       [ 8624],
       [ 9564],
       [ 9743],
       [ 6109],
       [18974],
       [ 7969],
       [ 8011],
       [ 6973]], dtype=int64)

In [83]:
y_predict= regressor.predict([[19, 1000007, 16, 1, 3, 1, 1, 1, 1, 14, 16]])
y_predict

array([17448.5])