In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset=pd.read_csv("resale values.csv")

In [3]:
dataset

vehicleType  yearOfRegistration    gearbox  kilometer notRepairedDamage  \
0          NaN                1993     manual     150000               NaN   
1        coupe                2011     manual     125000               yes   
2          suv                2004  automatic     125000               NaN   
3   kleinwagen                2001     manual     150000                no   
4   kleinwagen                2008     manual      90000                no   
5    limousine                1995     manual     150000               yes   
6       cabrio                2004     manual     150000                no   
7    limousine                1980     manual      40000                no   
8          bus                2014     manual      30000               NaN   
9   kleinwagen                1998     manual     150000               NaN   
10   limousine                2004     manual     150000                no   
11       kombi                2005     manual     150000               yes   
12       kombi                1995     manual     150000               NaN   
13       kombi                2004     manual     150000                no   
14         suv                2011     manual      70000                no   
15  kleinwagen                1910        NaN       5000               NaN   
16         NaN                2016        NaN     150000               NaN   
17  kleinwagen                2004  automatic     150000                no   
18         bus                2007     manual     150000                no   
19         bus                2004     manual     150000                no   
20       coupe                2009     manual     100000                no   
21   limousine                2002  automatic     150000                no   
22         NaN                2018     manual     150000                no   
23  kleinwagen                1997     manual     150000                no   
24   limousine                1990     manual     150000               yes   
25       kombi                2002  automatic     150000               yes   
26         NaN                2017     manual     125000                no   
27   limousine                2008     manual      60000                no   
28         bus                1981     manual       5000                no   
29  kleinwagen                2003     manual     150000                no   
30   limousine                1992  automatic     150000               NaN   
31       coupe                2001        NaN     150000               NaN   
32  kleinwagen                1993     manual     150000                no   
33         NaN                1997     manual     150000                no   
34  kleinwagen                2002     manual     150000                no   
35       kombi                2008     manual     150000                no   
36   limousine                2006     manual     150000                no   
37  kleinwagen                2013     manual      40000                no   
38      andere                2003     manual     150000                no   
39         NaN                2000     manual     150000               NaN   
40         bus                2006     manual     150000                no   
41   limousine                2010  automatic      80000                no   
42         NaN                2016     manual     150000               yes   
43       kombi                2000     manual     150000               yes   
44  kleinwagen                1997     manual     150000               yes   
45   limousine                1994     manual     100000               yes   
46       kombi                2005     manual     150000               yes   
47       kombi                1997  automatic     150000                no   
48         suv                2005     manual     150000               NaN   
49         bus                2001     manual     150000                no   
50  kleinwagen           

In [38]:
dataset.corr()

yearOfRegistration  kilometer  monthOfRegistration  \
yearOfRegistration             1.000000   0.260850             0.190402   
kilometer                      0.260850   1.000000             0.000555   
monthOfRegistration            0.190402   0.000555             1.000000   
price                          0.050319  -0.056052            -0.035004   

                        price  
yearOfRegistration   0.050319  
kilometer           -0.056052  
monthOfRegistration -0.035004  
price                1.000000

In [4]:
dataset.dropna()

vehicleType  yearOfRegistration    gearbox  kilometer notRepairedDamage  \
1        coupe                2011     manual     125000               yes   
3   kleinwagen                2001     manual     150000                no   
4   kleinwagen                2008     manual      90000                no   
5    limousine                1995     manual     150000               yes   
6       cabrio                2004     manual     150000                no   
7    limousine                1980     manual      40000                no   
10   limousine                2004     manual     150000                no   
11       kombi                2005     manual     150000               yes   
14         suv                2011     manual      70000                no   
17  kleinwagen                2004  automatic     150000                no   
18         bus                2007     manual     150000                no   
19         bus                2004     manual     150000                no   
20       coupe                2009     manual     100000                no   
21   limousine                2002  automatic     150000                no   
23  kleinwagen                1997     manual     150000                no   
24   limousine                1990     manual     150000               yes   
25       kombi                2002  automatic     150000               yes   
27   limousine                2008     manual      60000                no   
28         bus                1981     manual       5000                no   
29  kleinwagen                2003     manual     150000                no   
32  kleinwagen                1993     manual     150000                no   
34  kleinwagen                2002     manual     150000                no   
35       kombi                2008     manual     150000                no   
36   limousine                2006     manual     150000                no   
37  kleinwagen                2013     manual      40000                no   
38      andere                2003     manual     150000                no   
40         bus                2006     manual     150000                no   
41   limousine                2010  automatic      80000                no   
43       kombi                2000     manual     150000               yes   
45   limousine                1994     manual     100000               yes   
46       kombi                2005     manual     150000               yes   
47       kombi                1997  automatic     150000                no   
49         bus                2001     manual     150000                no   
50  kleinwagen                2009     manual      60000                no   
51         bus                2004     manual     150000                no   
52   limousine                1995     manual     150000                no   
56  kleinwagen                2013     manual      60000                no   
58   limousine                2003     manual     150000                no   
59   limousine                2013  automatic      40000                no   

   fuelType  monthOfRegistration          brand   price  
1    diesel                    5           audi  183000  
3    petrol                    6     volkswagen  158000  
4    diesel                    7          skoda  360000  
5    petrol                   10            bmw   65000  
6    petrol                    8        peugeot  220000  
7    petrol                    7     volkswagen   10000  
10   petrol                   12          mazda    2000  
11   diesel                   12     volkswagen    2799  
14   diesel                    3         nissan   17999  
17   petrol                    2        renault    1750  
18   diesel                    6           ford    7550  
19   petrol                    1  mercedes_benz    1850  
20   petrol                    4     volkswagen   10400  
21   petrol                    7            bmw    3699  
23   petrol 

In [5]:
dataset.corr()

yearOfRegistration  kilometer  monthOfRegistration  \
yearOfRegistration             1.000000   0.260850             0.190402   
kilometer                      0.260850   1.000000             0.000555   
monthOfRegistration            0.190402   0.000555             1.000000   
price                          0.050319  -0.056052            -0.035004   

                        price  
yearOfRegistration   0.050319  
kilometer           -0.056052  
monthOfRegistration -0.035004  
price                1.000000

In [6]:
dataset.isnull().any()

vehicleType             True
yearOfRegistration     False
gearbox                 True
kilometer              False
notRepairedDamage       True
fuelType                True
monthOfRegistration    False
brand                  False
price                  False
dtype: bool

In [7]:
dataset.corr()

yearOfRegistration  kilometer  monthOfRegistration  \
yearOfRegistration             1.000000   0.260850             0.190402   
kilometer                      0.260850   1.000000             0.000555   
monthOfRegistration            0.190402   0.000555             1.000000   
price                          0.050319  -0.056052            -0.035004   

                        price  
yearOfRegistration   0.050319  
kilometer           -0.056052  
monthOfRegistration -0.035004  
price                1.000000

In [8]:
 dataset=dataset.dropna(axis=1)

In [9]:
dataset

yearOfRegistration  kilometer  monthOfRegistration          brand   price
0                 1993     150000                    0     volkswagen  480000
1                 2011     125000                    5           audi  183000
2                 2004     125000                    8           jeep   98000
3                 2001     150000                    6     volkswagen  158000
4                 2008      90000                    7          skoda  360000
5                 1995     150000                   10            bmw   65000
6                 2004     150000                    8        peugeot  220000
7                 1980      40000                    7     volkswagen   10000
8                 2014      30000                    8           ford  145000
9                 1998     150000                    0     volkswagen     999
10                2004     150000                   12          mazda    2000
11                2005     150000                   12     volkswagen    2799
12                1995     150000                   11     volkswagen     999
13                2004     150000                    2     volkswagen    2500
14                2011      70000                    3         nissan   17999
15                1910       5000                    0           ford     450
16                2016     150000                    0     volkswagen     300
17                2004     150000                    2        renault    1750
18                2007     150000                    6           ford    7550
19                2004     150000                    1  mercedes_benz    1850
20                2009     100000                    4     volkswagen   10400
21                2002     150000                    7            bmw    3699
22                2018     150000                    5           opel    2900
23                1997     150000                    5           seat     450
24                1990     150000                   10  mercedes_benz     500
25                2002     150000                    9            bmw    2500
26                2017     125000                    4        citroen    5555
27                2008      60000                   11          honda    6900
28                1981       5000                    1     volkswagen    1990
29                2003     150000                    3           fiat     690
30                1992     150000                    9  mercedes_benz    1280
31                2001     150000                    0           opel    1200
32                1993     150000                    3     volkswagen     800
33                1997     150000                    3            bmw    2300
34                2002     150000                    4           ford     750
35                2008     150000                   10  mercedes_benz    7999
36                2006     150000                   10     volkswagen    6600
37                2013      40000                    4         nissan    7999
38                2003     150000                    8  mercedes_benz    1400
39                2000     150000                    2     volkswagen     800
40                2006     150000                    4  mercedes_benz    5000
41                2010      80000                   12  mercedes_benz   20300
42                2016     150000                    3           opel     150
43                2000     150000                    0     alfa_romeo     250
44                1997     150000                    3           fiat     350
45                1994     100000                    6           ford     600
46                2005     150000                    9  mercedes_benz    3300
47                1997     150000                   10         subaru    1600
48                2005     150000                    8          volvo    8000
49                2001     150000                    7     mitsubishi    1800
50                2009    

In [10]:
x=dataset.iloc[:,:-1].values

In [11]:
x

array([[1993, 150000, 0, 'volkswagen'],
       [2011, 125000, 5, 'audi'],
       [2004, 125000, 8, 'jeep'],
       [2001, 150000, 6, 'volkswagen'],
       [2008, 90000, 7, 'skoda'],
       [1995, 150000, 10, 'bmw'],
       [2004, 150000, 8, 'peugeot'],
       [1980, 40000, 7, 'volkswagen'],
       [2014, 30000, 8, 'ford'],
       [1998, 150000, 0, 'volkswagen'],
       [2004, 150000, 12, 'mazda'],
       [2005, 150000, 12, 'volkswagen'],
       [1995, 150000, 11, 'volkswagen'],
       [2004, 150000, 2, 'volkswagen'],
       [2011, 70000, 3, 'nissan'],
       [1910, 5000, 0, 'ford'],
       [2016, 150000, 0, 'volkswagen'],
       [2004, 150000, 2, 'renault'],
       [2007, 150000, 6, 'ford'],
       [2004, 150000, 1, 'mercedes_benz'],
       [2009, 100000, 4, 'volkswagen'],
       [2002, 150000, 7, 'bmw'],
       [2018, 150000, 5, 'opel'],
       [1997, 150000, 5, 'seat'],
       [1990, 150000, 10, 'mercedes_benz'],
       [2002, 150000, 9, 'bmw'],
       [2017, 125000, 4, 'citroen'],
 

In [12]:
y=dataset.iloc[:,4:].values

In [13]:
y

array([[480000],
       [183000],
       [ 98000],
       [158000],
       [360000],
       [ 65000],
       [220000],
       [ 10000],
       [145000],
       [   999],
       [  2000],
       [  2799],
       [   999],
       [  2500],
       [ 17999],
       [   450],
       [   300],
       [  1750],
       [  7550],
       [  1850],
       [ 10400],
       [  3699],
       [  2900],
       [   450],
       [   500],
       [  2500],
       [  5555],
       [  6900],
       [  1990],
       [   690],
       [  1280],
       [  1200],
       [   800],
       [  2300],
       [   750],
       [  7999],
       [  6600],
       [  7999],
       [  1400],
       [   800],
       [  5000],
       [ 20300],
       [   150],
       [   250],
       [   350],
       [   600],
       [  3300],
       [  1600],
       [  8000],
       [  1800],
       [  6800],
       [  2990],
       [     1],
       [  2400],
       [  1222],
       [   250],
       [ 14500],
       [  8390],
       [  3850

In [14]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
x[:,3]=lb.fit_transform(x[:,3])

In [15]:
x

array([[1993, 150000, 0, 18],
       [2011, 125000, 5, 1],
       [2004, 125000, 8, 7],
       [2001, 150000, 6, 18],
       [2008, 90000, 7, 16],
       [1995, 150000, 10, 2],
       [2004, 150000, 8, 13],
       [1980, 40000, 7, 18],
       [2014, 30000, 8, 5],
       [1998, 150000, 0, 18],
       [2004, 150000, 12, 8],
       [2005, 150000, 12, 18],
       [1995, 150000, 11, 18],
       [2004, 150000, 2, 18],
       [2011, 70000, 3, 11],
       [1910, 5000, 0, 5],
       [2016, 150000, 0, 18],
       [2004, 150000, 2, 14],
       [2007, 150000, 6, 5],
       [2004, 150000, 1, 9],
       [2009, 100000, 4, 18],
       [2002, 150000, 7, 2],
       [2018, 150000, 5, 12],
       [1997, 150000, 5, 15],
       [1990, 150000, 10, 9],
       [2002, 150000, 9, 2],
       [2017, 125000, 4, 3],
       [2008, 60000, 11, 6],
       [1981, 5000, 1, 18],
       [2003, 150000, 3, 4],
       [1992, 150000, 9, 9],
       [2001, 150000, 0, 12],
       [1993, 150000, 3, 18],
       [1997, 150000, 3, 2],

In [16]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(categorical_features=[3])
x=oh.fit_transform(x).toarray()

C:\Users\purushotham\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\purushotham\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [17]:
x.shape

(60, 23)

In [25]:
x=x[:,15:]

In [26]:
x

array([[0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 1.993e+03,
        1.500e+05, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.011e+03,
        1.250e+05, 5.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.004e+03,
        1.250e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 2.001e+03,
        1.500e+05, 6.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.008e+03,
        9.000e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.995e+03,
        1.500e+05, 1.000e+01],
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.004e+03,
        1.500e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 1.980e+03,
        4.000e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.014e+03,
        3.000e+04, 8.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.0

In [27]:
x.shape

(60, 8)

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [30]:
y_predict=regressor.predict(x_test)

In [31]:
y_predict

array([  5555.,   7999.,  23490.,   1990.,   2799.,  98000.,    750.,
         3850.,   5000.,   2900., 360000.,   2495.])

In [37]:
regressor.predict(np.array([[1,0,0,1,0,2000, 15000, 0]]))

array([145000.])